name: Package

on:
  push:
    branches:
      - main
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package
        run: |
          wget https://github.com/goreleaser/nfpm/releases/download/v2.26.0/nfpm_2.26.0_Linux_x86_64.tar.gz
          tar -xvf nfpm_2.26.0_Linux_x86_64.tar.gz
          ./nfpm package --packager deb
          ./nfpm package --packager rpm
      - uses: actions/upload-artifact@v3
        with:
          name: obs-service-linglong
          path: |
            *.deb
            *.rpm
